[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[project]
name = "stamp"
version = "1.3.0"
authors = [
    { name = "Omar El Nahhas", email = "omar.el_nahhas@tu-dresden.de" },
    { name = "Marko van Treeck", email = "markovantreeck@gmail.com" },
    { name = "Georg Wölflein", email = "georgw7777@gmail.com" },
    { name = "Tim Lenz", email = "tim.lenz@tu-dresden.de" },
    { name = "Laura Žigutytė", email = "laura.zigutyte@tu-dresden.de" },
    { name = "Cornelius Kummer", email = "cornelius.kummer@tu-dresden.de" },
]
description = "A protocol for Solid Tumor Associative Modeling in Pathology"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "einops>=0.8.0",
    "fastai>=2.7.18",
    "gdown>=5.2.0",
    "h5py>=3.12.1",
    "matplotlib>=3.9.2",
    "opencv-python>=4.10.0.84",
    "openpyxl>=3.1.5",
    "openslide-python>=1.4.1",
    "pandas>=2.2.3",
    "pyyaml>=6.0.2",
    "scikit-learn>=1.5.2",
    "torch>=2.5.1",
    "tqdm>=4.66.6",
    "UNI@git+https://github.com/mahmoodlab/UNI.git#egg=f8f32c60a1d86805fdcb7317673c45318dac4806",
]

[project.optional-dependencies]
accelerate = ["xformers>=0.0.28.post3"]

[tool.uv]
default-groups = ["accelerate"]

[project.scripts]
"stamp" = "stamp.__main__:main"

[project.urls]
"Homepage" = "https://github.com/KatherLab/STAMP"
"Bug Tracker" = "https://github.com/KatherLab/STAMP/issues"

[tool.hatch.build]
include = ["stamp/**/*"]
